"""Official Python SDK for the Opa link shortener API (https://api.opa.sh/v1)."""

from ._internal.request_options import RequestOptions
from ._internal.version import __version__
from .client import DEFAULT_BASE_URL, AsyncOpaClient, OpaClient
from .errors import (
    AuthenticationError,
    ConflictError,
    NetworkError,
    NotFoundError,
    OpaError,
    PermissionDeniedError,
    RateLimitError,
    ServerError,
    ValidationError,
)
from .models import (
    AnalyticsEvent,
    AnalyticsRange,
    AnalyticsSummary,
    AnalyticsTimeseries,
    AnalyticsTimeseriesPoint,
    ArchiveLinkResult,
    BulkArchiveResult,
    BulkMoveResult,
    BulkRestoreResult,
    BulkTagResult,
    Domain,
    Folder,
    Link,
    LinkSummary,
    LinkTargeting,
    Page,
    QrSettings,
    RestoreLinkResult,
    Tag,
)
from .resources import (
    AnalyticsResource,
    AsyncAnalyticsResource,
    AsyncDomainsResource,
    AsyncLinksResource,
    AsyncTrackResource,
    DomainsResource,
    LinksResource,
    TrackResource,
)

__all__ = [
    "__version__",
    "DEFAULT_BASE_URL",
    "OpaClient",
    "AsyncOpaClient",
    "RequestOptions",
    # errors
    "OpaError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "RateLimitError",
    "ServerError",
    "NetworkError",
    # resources
    "LinksResource",
    "AsyncLinksResource",
    "AnalyticsResource",
    "AsyncAnalyticsResource",
    "DomainsResource",
    "AsyncDomainsResource",
    "TrackResource",
    "AsyncTrackResource",
    # models
    "Link",
    "LinkSummary",
    "LinkTargeting",
    "QrSettings",
    "Tag",
    "Folder",
    "Domain",
    "Page",
    "ArchiveLinkResult",
    "RestoreLinkResult",
    "BulkArchiveResult",
    "BulkRestoreResult",
    "BulkMoveResult",
    "BulkTagResult",
    "AnalyticsRange",
    "AnalyticsSummary",
    "AnalyticsTimeseries",
    "AnalyticsTimeseriesPoint",
    "AnalyticsEvent",
]
